### ISSUE TITLE
Errors on 'npm start'

### ISSUE THREAD

**Issue by mohsinht** [asyrafduyshart/antd-firebase-dashboard#2]
On 'npm start' after cloning and setting up the project, I get the following errors:

`Warning: DISABLE_ESLINT is deprecated, use ESLINT=none instead has been deprecated.
TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:695:11)
    at nodeDeprecate (\antd-firebase-dashboard-master\antd-firebase-dashboard-master\node_modules\deprecate\index.js:22:22)
    at deprecate (\antd-firebase-dashboard-master\antd-firebase-dashboard-master\node_modules\deprecate\index.js:11:3)
    at Object.<anonymous> (\antd-firebase-dashboard-master\antd-firebase-dashboard-master\node_modules\af-webpack\lib\getConfig.js:81:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (\antd-firebase-dashboard-master\antd-firebase-dashboard-master\node_modules\af-webpack\getConfig.js:1:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

**Comment by asyrafduyshart** [comment]
i already update version 2
